<?php
if (!defined('ABSPATH')) exit;
final class SEO_Manager_404 {
 public static function init():void{add_action('seom_cleanup_404',[__CLASS__,'cleanup']);if(!wp_next_scheduled('seom_cleanup_404'))wp_schedule_event(time()+3600,'daily','seom_cleanup_404');add_action('wp_ajax_seom_delete_404',[__CLASS__,'delete']);add_action('wp_ajax_seom_clear_404',[__CLASS__,'clear']);}
 public static function capture():void{if(!is_404()||is_admin()||wp_doing_ajax())return;global $wpdb;$table=$wpdb->prefix.'seom_404_logs';$url=substr(seom_clean_path(wp_unslash($_SERVER['REQUEST_URI']??'')),0,255);$ref=substr(sanitize_text_field(wp_unslash($_SERVER['HTTP_REFERER']??'')),0,255);$ua=substr(sanitize_text_field(wp_unslash($_SERVER['HTTP_USER_AGENT']??'')),0,1000);$ip=(string)($_SERVER['REMOTE_ADDR']??'');$hash=hash('sha256',wp_salt('auth').$ip);$row=$wpdb->get_row($wpdb->prepare("SELECT id FROM $table WHERE url=%s LIMIT 1",$url));$now=current_time('mysql');if($row)$wpdb->query($wpdb->prepare("UPDATE $table SET hits=hits+1,last_seen=%s,referrer=%s,user_agent=%s,ip_hash=%s WHERE id=%d",$now,$ref,$ua,$hash,$row->id));else $wpdb->insert($table,['url'=>$url,'referrer'=>$ref,'user_agent'=>$ua,'ip_hash'=>$hash,'hits'=>1,'first_seen'=>$now,'last_seen'=>$now]);}
 public static function cleanup():void{global $wpdb;$days=max(1,(int)seom_get('404_retention',30));$wpdb->query($wpdb->prepare("DELETE FROM {$wpdb->prefix}seom_404_logs WHERE last_seen < %s",gmdate('Y-m-d H:i:s',time()-DAY_IN_SECONDS*$days)));}
 public static function delete():void{check_ajax_referer('seom_admin','nonce');if(!current_user_can('manage_options'))wp_send_json_error();global $wpdb;$wpdb->delete($wpdb->prefix.'seom_404_logs',['id'=>absint($_POST['id']??0)],['%d']);wp_send_json_success();}
 public static function clear():void{check_ajax_referer('seom_admin','nonce');if(!current_user_can('manage_options'))wp_send_json_error();global $wpdb;$wpdb->query("TRUNCATE TABLE {$wpdb->prefix}seom_404_logs");wp_send_json_success();}
}
