<?php
if (!defined('ABSPATH')) exit;
final class SEO_Manager_Taxonomy {
 public static function init():void{add_action('category_add_form_fields',[__CLASS__,'fields']);add_action('post_tag_add_form_fields',[__CLASS__,'fields']);add_action('created_term',[__CLASS__,'save'],10,3);add_action('category_edit_form_fields',[__CLASS__,'edit_fields']);add_action('post_tag_edit_form_fields',[__CLASS__,'edit_fields']);add_action('edited_term',[__CLASS__,'save'],10,3);add_action('admin_init',[__CLASS__,'register_cpt_taxonomies']);}
 public static function register_cpt_taxonomies():void{foreach(get_taxonomies(['public'=>true],'names') as $tax){if(in_array($tax,['category','post_tag'],true))continue;add_action($tax.'_add_form_fields',[__CLASS__,'fields']);add_action($tax.'_edit_form_fields',[__CLASS__,'edit_fields']);add_action('created_term',[__CLASS__,'save'],10,3);add_action('edited_term',[__CLASS__,'save'],10,3);}}
 private static function vals($term_id):array{return['title'=>get_term_meta($term_id,'_seom_title',true),'description'=>get_term_meta($term_id,'_seom_description',true),'canonical'=>get_term_meta($term_id,'_seom_canonical',true),'robots'=>get_term_meta($term_id,'_seom_robots',true)];}
 public static function fields():void{echo '<div class="form-field"><label>SEO Title</label><input type="text" name="seom_tax_title"></div><div class="form-field"><label>Meta Description</label><textarea name="seom_tax_description"></textarea></div><div class="form-field"><label>Canonical URL</label><input type="url" name="seom_tax_canonical"></div><div class="form-field"><label>Robots</label><input type="text" name="seom_tax_robots" placeholder="index,follow"></div>';}
 public static function edit_fields(WP_Term $term):void{$v=self::vals($term->term_id);echo '<tr class="form-field"><th><label>SEO Title</label></th><td><input type="text" name="seom_tax_title" value="'.esc_attr($v['title']).'"></td></tr><tr class="form-field"><th><label>Meta Description</label></th><td><textarea name="seom_tax_description">'.esc_textarea($v['description']).'</textarea></td></tr><tr class="form-field"><th><label>Canonical URL</label></th><td><input type="url" name="seom_tax_canonical" value="'.esc_attr($v['canonical']).'"></td></tr><tr class="form-field"><th><label>Robots</label></th><td><input type="text" name="seom_tax_robots" value="'.esc_attr($v['robots']).'" placeholder="index,follow"></td></tr>';}
 public static function save(int $term_id,int $tt_id,string $taxonomy):void{if(isset($_POST['seom_tax_title']))update_term_meta($term_id,'_seom_title',sanitize_text_field(wp_unslash($_POST['seom_tax_title'])));if(isset($_POST['seom_tax_description']))update_term_meta($term_id,'_seom_description',sanitize_textarea_field(wp_unslash($_POST['seom_tax_description'])));if(isset($_POST['seom_tax_canonical']))update_term_meta($term_id,'_seom_canonical',esc_url_raw(wp_unslash($_POST['seom_tax_canonical'])));if(isset($_POST['seom_tax_robots']))update_term_meta($term_id,'_seom_robots',sanitize_text_field(wp_unslash($_POST['seom_tax_robots'])));}
}
