<?php
if (!defined('ABSPATH')) exit;
final class SEO_Manager_DB {
 public static function activate():void{ global $wpdb; $c=$wpdb->get_charset_collate(); require_once ABSPATH.'wp-admin/includes/upgrade.php';
  $r=$wpdb->prefix.'seom_redirects'; $e=$wpdb->prefix.'seom_404_logs'; $a=$wpdb->prefix.'seom_audit'; $i=$wpdb->prefix.'seom_indexing_logs';
  dbDelta("CREATE TABLE $r (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, source varchar(255) NOT NULL, destination varchar(2048) NOT NULL, type smallint(3) NOT NULL DEFAULT 301, enabled tinyint(1) NOT NULL DEFAULT 1, hits bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY(id), UNIQUE KEY source (source(191)), KEY enabled (enabled)) $c;");
  dbDelta("CREATE TABLE $e (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, url varchar(255) NOT NULL, referrer varchar(255) NOT NULL DEFAULT '', user_agent text NOT NULL, ip_hash char(64) NOT NULL DEFAULT '', hits int(10) unsigned NOT NULL DEFAULT 1, first_seen datetime NOT NULL, last_seen datetime NOT NULL, PRIMARY KEY(id), UNIQUE KEY url_hash (url(191)), KEY last_seen (last_seen), KEY hits (hits)) $c;");
  dbDelta("CREATE TABLE $a (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, run_id char(32) NOT NULL, issue_type varchar(60) NOT NULL, object_id bigint(20) unsigned NOT NULL DEFAULT 0, url varchar(2048) NOT NULL DEFAULT '', message text NOT NULL, severity varchar(12) NOT NULL DEFAULT 'warning', created_at datetime NOT NULL, PRIMARY KEY(id), KEY run_id(run_id), KEY severity(severity)) $c;");
  dbDelta("CREATE TABLE $i (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, url varchar(2048) NOT NULL, action varchar(20) NOT NULL DEFAULT 'update', status varchar(20) NOT NULL DEFAULT 'queued', response_code int(11) NOT NULL DEFAULT 0, message text NOT NULL, object_id bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, attempts int(10) unsigned NOT NULL DEFAULT 0, provider varchar(30) NOT NULL DEFAULT 'google', PRIMARY KEY(id), KEY url_hash (url(191)), KEY status (status), KEY action (action), KEY object_id (object_id), KEY created_at (created_at)) $c;");
  $defaults=['version'=>SEOM_VERSION,'title_format'=>'%%title%% | %%sitename%%','site_type'=>'organization','org_name'=>get_bloginfo('name'),'org_logo'=>'','enable_sitemap'=>1,'enable_schema'=>1,'enable_og'=>1,'enable_twitter'=>1,'twitter_card'=>'summary_large_image','404_retention'=>30,'default_description'=>get_bloginfo('description'),'default_robots'=>'index,follow','robots_custom'=>'','default_social_image'=>'','search_noindex'=>1,'date_noindex'=>1,'author_noindex'=>0,'category_noindex'=>0,'tag_noindex'=>1,'breadcrumbs'=>1,'schema_type'=>'auto','local_enabled'=>0,'local_business_type'=>'LocalBusiness','local_phone'=>'','local_email'=>'','local_address'=>'','local_city'=>'','local_state'=>'','local_postcode'=>'','local_country'=>'','local_hours'=>'','local_lat'=>'','local_lng'=>'','local_price_range'=>'','google_client_id'=>'','google_client_secret'=>'','google_connected'=>0,'google_email'=>'','google_name'=>'','google_access_token'=>'','google_refresh_token'=>'','google_expires_at'=>0,'google_sites'=>[],'google_selected_site'=>'','google_notify_email'=>get_option('admin_email'),'google_monitor_enabled'=>1,'google_monitor_frequency'=>'daily','google_updates_checked'=>0,'google_updates_history'=>[],'google_update_ids'=>[],'google_analytics_rows'=>[],'google_analytics_synced'=>0,'google_verification'=>'','bing_verification'=>'','yandex_verification'=>'','baidu_verification'=>'','analytics_id'=>'','nofollow_external'=>0,'open_external_blank'=>1,'nofollow_image_links'=>0,'noindex_empty_archives'=>1,'redirect_attachments'=>1,'redirect_orphan_attachments'=>0,'orphan_attachment_url'=>'','strip_category_base'=>0,'llms_enabled'=>0,'llms_extra'=>'','indexnow_enabled'=>0,'indexnow_key'=>'','indexnow_auto_update'=>1,'indexnow_auto_delete'=>1,'indexnow_submit_homepage'=>1,'indexnow_daily_limit'=>200,'bing_api_enabled'=>0,'bing_api_key'=>'','news_sitemap'=>0,'video_sitemap'=>0,'news_publisher'=>get_bloginfo('name'),'news_language'=>get_bloginfo('language'),'indexing_enabled'=>0,'indexing_auto_publish'=>1,'indexing_auto_delete'=>1,'indexing_strict_mode'=>1,'indexing_service_account'=>'','indexing_last_sync'=>0,'indexing_daily_limit'=>200,'redirect_debug'=>0,'redirect_fallback'=>'404','redirect_fallback_url'=>'','redirect_default_type'=>301,'redirect_auto_post'=>0,'redirect_preserve_query'=>1,'image_auto_alt'=>0,'image_auto_title'=>0,'video_auto_schema'=>0,'wc_schema'=>1,'wc_og'=>1,'wc_noindex_hidden'=>1];
  foreach($defaults as $k=>$v) if(get_option('seom_'.$k,null)===null) update_option('seom_'.$k,$v,false);
  update_option('seom_version',SEOM_VERSION,false); if(class_exists('SEO_Manager_RankMath_Parity')) SEO_Manager_RankMath_Parity::ensure_roles(); flush_rewrite_rules();
 }
 public static function tables_exist():bool{global $wpdb;$tables=[$wpdb->prefix.'seom_redirects',$wpdb->prefix.'seom_404_logs',$wpdb->prefix.'seom_audit',$wpdb->prefix.'seom_indexing_logs'];foreach($tables as $t){$found=$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$t));if($found!==$t)return false;}return true;}
 public static function deactivate():void{wp_clear_scheduled_hook('seom_cleanup_404');wp_clear_scheduled_hook('seom_daily_audit');wp_clear_scheduled_hook('seom_google_sync');flush_rewrite_rules();}
}
