<?php
if (!defined('ABSPATH')) exit;
final class SEO_Manager_Audit {
 public static function init():void{add_action('admin_post_seom_run_audit',[__CLASS__,'run']);add_action('admin_post_seom_clear_audit',[__CLASS__,'clear']);}
 public static function run():void{if(!current_user_can('manage_options')||!check_admin_referer('seom_run_audit'))wp_die('Unauthorized');global $wpdb;$run=md5(uniqid('',true));$wpdb->query("TRUNCATE TABLE {$wpdb->prefix}seom_audit");$issues=[];$types=seom_post_types();foreach($types as $pt){$ids=get_posts(['post_type'=>$pt,'post_status'=>'publish','posts_per_page'=>200,'fields'=>'ids','orderby'=>'ID','order'=>'ASC']);foreach($ids as $id){$a=SEO_Manager_Content_Analysis::analyze($id);if(!$a)continue;if(seom_meta($id,'title','')==='')$issues[]=['severity'=>'critical','issue_type'=>'missing_title','object_id'=>$id,'url'=>get_permalink($id),'message'=>'Missing SEO title'];if(seom_meta($id,'description','')==='')$issues[]=['severity'=>'critical','issue_type'=>'missing_description','object_id'=>$id,'url'=>get_permalink($id),'message'=>'Missing meta description'];if($a['h1']!==1)$issues[]=['severity'=>'warning','issue_type'=>'h1','object_id'=>$id,'url'=>get_permalink($id),'message'=>'H1 count is '.$a['h1']];if($a['images']>$a['images_with_alt'])$issues[]=['severity'=>'warning','issue_type'=>'image_alt','object_id'=>$id,'url'=>get_permalink($id),'message'=>'Some images lack ALT text'];if($a['links']===0)$issues[]=['severity'=>'warning','issue_type'=>'links','object_id'=>$id,'url'=>get_permalink($id),'message'=>'No links detected'];}}
 foreach($issues as $i){$wpdb->insert($wpdb->prefix.'seom_audit',['run_id'=>$run,'issue_type'=>$i['issue_type'],'object_id'=>$i['object_id'],'url'=>$i['url'],'message'=>$i['message'],'severity'=>$i['severity'],'created_at'=>current_time('mysql')]);}$redirect=add_query_arg(['page'=>'seo-manager-content','subtab'=>'audit','run'=>$run],admin_url('admin.php'));wp_safe_redirect($redirect);exit;}
 public static function clear():void{if(!current_user_can('manage_options')||!check_admin_referer('seom_clear_audit'))wp_die('Unauthorized');global $wpdb;$wpdb->query("TRUNCATE TABLE {$wpdb->prefix}seom_audit");wp_safe_redirect(seom_admin_page_url('content','audit'));exit;}
 public static function latest():array{global $wpdb;return $wpdb->get_results("SELECT * FROM {$wpdb->prefix}seom_audit ORDER BY id DESC LIMIT 500")?:[];}
}
