<?php if (!defined('ABSPATH')) exit;
$connected = SEO_Manager_Google_Business_Profile::connected();
$accounts = (array) seom_get('gbp_accounts', array());
$locations = (array) seom_get('gbp_locations', array());
$reviews = SEO_Manager_Google_Business_Profile::read_temp('gbp_reviews', array());
$posts = SEO_Manager_Google_Business_Profile::read_temp('gbp_posts', array());
$entityResults = SEO_Manager_Google_Business_Profile::read_temp('gbp_entity_results', array());
$selectedLocation = (string) seom_get('gbp_selected_location','');
$current = array(); foreach ($locations as $l) if (($l['name']??'') === $selectedLocation) $current=$l;
$perf = SEO_Manager_Google_Business_Profile::read_temp('gbp_performance', array());
$knowledgeChecks = array(
  'entity_name' => (string)seom_get('knowledge_entity_name','') !== '',
  'entity_description' => (string)seom_get('knowledge_entity_description','') !== '',
  'entity_id' => (string)seom_get('knowledge_entity_id','') !== '',
  'place_id' => (string)seom_get('knowledge_place_id','') !== '',
  'google_maps_url' => (string)seom_get('knowledge_google_maps_url','') !== '',
  'entity_logo' => (string)seom_get('knowledge_entity_logo','') !== '',
  'entity_sameas' => (string)seom_get('knowledge_entity_sameas','') !== '',
);
$knowledgeScore = (int)round(array_sum(array_map(function($v){return $v?1:0;},$knowledgeChecks)) / count($knowledgeChecks) * 100);
?>
<div class="seom-panel seom-hero"><div><div class="seom-eyebrow">GOOGLE BUSINESS PROFILE</div><h1>Business Profile & Knowledge Panel</h1><p>Manage supported Google Business Profile data, reviews, posts and performance from WordPress.</p></div><div><?php if($connected): ?><span class="seom-pill">Connected<?php echo seom_get('gbp_email')?' · '.esc_html(seom_get('gbp_email')):''; ?></span><?php else: ?><span class="seom-pill">Not connected</span><?php endif; ?></div></div>
<?php if(isset($_GET['gbp_error'])): ?><div class="notice notice-error"><p><?php echo esc_html(isset($_GET['gbp_message']) ? rawurldecode(wp_unslash($_GET['gbp_message'])) : 'Google Business Profile request failed. Check API access, permissions and the selected location.'); ?></p></div><?php endif; ?>
<?php if(isset($_GET['gbp_connected'])): ?><div class="notice notice-success"><p>Google Business Profile account connected.</p></div><?php endif; ?>
<?php if(isset($_GET['gbp_synced'])): ?><div class="notice notice-success"><p>Accounts and locations synced successfully.</p></div><?php endif; ?>
<div class="seom-two">
  <div class="seom-panel"><h3>Connection</h3><p>Use the same Google OAuth client ID/secret already configured in Google & Integrations, or override them here.</p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><?php wp_nonce_field('seom_gbp_save_credentials'); ?><input type="hidden" name="action" value="seom_gbp_save_credentials"><label class="seom-full-label">GBP OAuth Client ID<input class="widefat" name="gbp_client_id" value="<?php echo esc_attr(seom_get('gbp_client_id','')); ?>" placeholder="Uses Google & Integrations client ID when blank"></label><label class="seom-full-label">GBP OAuth Client Secret<input class="widefat" type="password" name="gbp_client_secret" value="" placeholder="<?php echo seom_get('gbp_client_secret','')?'Saved securely':'Optional override'; ?>"></label><label class="seom-full-label">Knowledge Graph API Key<input class="widefat" name="gbp_knowledge_graph_key" value="<?php echo esc_attr(seom_get('gbp_knowledge_graph_key','')); ?>"></label><p><button class="button button-primary">Save Integration Settings</button></p></form><?php if($connected): ?><a class="button" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=seom_gbp_disconnect'),'seom_gbp_disconnect')); ?>">Disconnect GBP</a><?php else: ?><a class="button button-primary" href="<?php echo esc_url(admin_url('admin-post.php?action=seom_gbp_start')); ?>">Connect Google Business Profile</a><?php endif; ?><p class="description">OAuth callback: <code><?php echo esc_html(SEO_Manager_Google_Business_Profile::redirect_uri()); ?></code></p></div>
  <div class="seom-panel"><h3>Location selector</h3><?php if($connected): ?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="seom-form-grid"><input type="hidden" name="action" value="seom_gbp_select"><?php wp_nonce_field('seom_gbp_select'); ?><label>Business Profile account<select class="widefat" name="gbp_selected_account"><?php foreach($accounts as $a): ?><option value="<?php echo esc_attr($a['name']); ?>" <?php selected(seom_get('gbp_selected_account',''),$a['name']); ?>><?php echo esc_html(($a['accountName']??'Account').' · '.($a['type']??'')); ?></option><?php endforeach; ?></select></label><label>Location<select class="widefat" name="gbp_selected_location"><option value="">Select location</option><?php foreach($locations as $l): ?><option value="<?php echo esc_attr($l['name']); ?>" <?php selected($selectedLocation,$l['name']); ?>><?php echo esc_html($l['title'].' — '.$l['address']); ?></option><?php endforeach; ?></select></label><div class="seom-full"><button class="button button-primary">Select Account & Location</button> <a class="button" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=seom_gbp_sync'),'seom_gbp_sync')); ?>">Sync</a></div></form><?php else: ?><p>Connect a Google account to load Business Profile accounts and locations.</p><?php endif; ?></div>
</div>
<?php if($connected && $current): ?>
<div class="seom-panel"><div class="seom-actions"><div><h3>Profile editor</h3><p>Edit supported Business Profile fields. Google may moderate or reject changes.</p></div><a class="button" target="_blank" rel="noopener" href="<?php echo esc_url('https://business.google.com/edit/l/u'.rawurlencode(basename($current['name']))); ?>">Open in Google Business Profile</a></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="seom-form-grid"><input type="hidden" name="action" value="seom_gbp_save_location"><input type="hidden" name="location_name" value="<?php echo esc_attr($current['name']); ?>"><?php wp_nonce_field('seom_gbp_save_location'); ?><label>Business name<input name="title" value="<?php echo esc_attr($current['title']); ?>"></label><label>Website URL<input type="url" name="website_uri" value="<?php echo esc_attr($current['websiteUri']); ?>"></label><label>Primary phone<input name="phone" value="<?php echo esc_attr($current['phone']); ?>"></label><label>Store code<input value="<?php echo esc_attr($current['storeCode']); ?>" disabled></label><div class="seom-full"><button class="button button-primary">Update Google Business Profile</button> <?php if($current['mapsUri']): ?><a class="button" target="_blank" rel="noopener" href="<?php echo esc_url($current['mapsUri']); ?>">Open Maps</a><?php endif; ?></div></form></div>
<div class="seom-two">
<div class="seom-panel"><div class="seom-actions"><div><h3>Google Reviews</h3><p>Read reviews and reply or remove your reply. Review responses require proper authorization.</p></div><a class="button" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=seom_gbp_sync'),'seom_gbp_sync')); ?>">Refresh</a></div><?php if(!$reviews): ?><p>No cached reviews yet.</p><?php else: ?><div class="seom-table-scroll"><table class="widefat striped"><thead><tr><th>Reviewer</th><th>Rating</th><th>Review</th><th>Reply</th></tr></thead><tbody><?php foreach($reviews as $r): ?><tr><td><?php echo esc_html($r['reviewer']??''); ?></td><td><?php echo esc_html($r['rating']??''); ?></td><td><?php echo esc_html($r['comment']??''); ?></td><td><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="seom_gbp_reply_review"><input type="hidden" name="review_name" value="<?php echo esc_attr($r['name']??''); ?>"><?php wp_nonce_field('seom_gbp_reply_review'); ?><textarea name="reply" rows="3" placeholder="Write a reply"><?php echo esc_textarea($r['reply']??''); ?></textarea><button class="button button-primary">Save Reply</button></form><?php if(!empty($r['reply'])): ?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" style="margin-top:6px"><input type="hidden" name="action" value="seom_gbp_delete_reply"><input type="hidden" name="review_name" value="<?php echo esc_attr($r['name']??''); ?>"><?php wp_nonce_field('seom_gbp_delete_reply'); ?><button class="button">Delete Reply</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div>
<div class="seom-panel"><h3>Create Google Post</h3><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="seom-form-grid"><input type="hidden" name="action" value="seom_gbp_create_post"><?php wp_nonce_field('seom_gbp_create_post'); ?><label class="seom-full">Post text<textarea name="summary" rows="5" required></textarea></label><label>Topic<select name="topic_type"><option value="STANDARD">Standard</option><option value="EVENT">Event</option><option value="OFFER">Offer</option></select></label><label>CTA<select name="action_type"><option>LEARN_MORE</option><option>BOOK</option><option>ORDER</option><option>SHOP</option><option>SIGN_UP</option><option>CALL</option></select></label><label class="seom-full">CTA URL<input type="url" name="cta_url"></label><label>Coupon Code<input name="coupon_code"></label><label>Redeem URL<input type="url" name="redeem_url"></label><label class="seom-full">Offer terms<textarea name="terms" rows="2"></textarea></label><div class="seom-full"><button class="button button-primary">Publish Google Post</button></div></form><hr><?php if($posts): ?><strong>Recent posts</strong><ul><?php foreach(array_slice($posts,0,10) as $p): ?><li><?php echo esc_html(($p['topicType']??'').': '.($p['summary']??'')); ?> <?php if(!empty($p['searchUrl'])): ?><a target="_blank" rel="noopener" href="<?php echo esc_url($p['searchUrl']); ?>">View</a><?php endif; ?></li><?php endforeach; ?></ul><?php endif; ?></div>
</div>
<div class="seom-panel"><div class="seom-actions"><div><h3>Location Managers</h3><p>Invite or remove managers for the selected Business Profile location.</p></div></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="seom-tool-row"><input type="hidden" name="action" value="seom_gbp_invite_admin"><?php wp_nonce_field('seom_gbp_invite_admin'); ?><input type="email" name="admin_email" placeholder="manager@example.com" required><select name="admin_role"><option value="MANAGER">Manager</option><option value="SITE_MANAGER">Site Manager</option></select><button class="button button-primary">Invite</button></form><?php $admins=SEO_Manager_Google_Business_Profile::read_temp('gbp_admins',array()); if($admins): ?><table class="widefat striped" style="margin-top:12px"><thead><tr><th>Email</th><th>Role</th><th>Action</th></tr></thead><tbody><?php foreach($admins as $a): ?><tr><td><?php echo esc_html($a['adminName']??''); ?></td><td><?php echo esc_html($a['role']??''); ?></td><td><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><?php wp_nonce_field('seom_gbp_remove_admin'); ?><input type="hidden" name="action" value="seom_gbp_remove_admin"><input type="hidden" name="admin_name" value="<?php echo esc_attr($a['name']??''); ?>"><button class="button">Remove</button></form></td></tr><?php endforeach; ?></tbody></table><?php else: ?><p>No cached manager data yet.</p><?php endif; ?></div>
<div class="seom-two"><div class="seom-panel"><div class="seom-actions"><div><h3>Business Profile Performance</h3><p>Fetch recent Business Profile performance metrics for the selected location.</p></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="seom_gbp_refresh_performance"><?php wp_nonce_field('seom_gbp_performance'); ?><button class="button button-primary">Refresh Performance</button></form></div><pre class="seom-api-result"><?php echo esc_html(wp_json_encode($perf, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)); ?></pre></div>
<div class="seom-panel"><h3>Google Business Profile profile health</h3><?php $profileItems=array('Business name','Website URL','Primary phone','Maps link','Selected location'); foreach($profileItems as $idx=>$label): $ok=($idx===0?(bool)$current['title']:($idx===1?(bool)$current['websiteUri']:($idx===2?(bool)$current['phone']:($idx===3?(bool)$current['mapsUri']:true)))); ?><div class="seom-toggle-row"><span><strong><?php echo esc_html($label); ?></strong><small><?php echo $ok?'Configured':'Add or verify this field in Google Business Profile.'; ?></small></span><span class="seom-pill"><?php echo $ok?'Ready':'Needs attention'; ?></span></div><?php endforeach; ?></div></div>
<?php endif; ?>
<div class="seom-panel"><div class="seom-actions"><div><h3>Knowledge Panel & Entity SEO</h3><p>Build consistent entity signals across your website and Google Business Profile. Google does not expose an API that lets site owners directly edit or force a Knowledge Panel.</p></div><div class="seom-score-orb"><strong><?php echo esc_html($knowledgeScore); ?></strong><span>readiness</span></div></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="seom-form-grid"><input type="hidden" name="action" value="seom_save_entity_schema"><?php wp_nonce_field('seom_save_entity_schema'); ?>

<label>Entity / Brand Name<input name="entity_name" value="<?php echo esc_attr(seom_get('knowledge_entity_name','')); ?>"></label>
<label>Entity Type<input name="entity_type" value="<?php echo esc_attr(seom_get('knowledge_entity_type','Organization')); ?>" placeholder="Organization"></label>
<label>Knowledge Graph / Entity ID<input name="entity_id" value="<?php echo esc_attr(seom_get('knowledge_entity_id','')); ?>" placeholder="Optional kg:/... ID"></label>
<label>Google Place ID<input name="place_id" value="<?php echo esc_attr(seom_get('knowledge_place_id','')); ?>"></label>
<label>Google Maps URL<input type="url" name="google_maps_url" value="<?php echo esc_attr(seom_get('knowledge_google_maps_url','')); ?>"></label>
<label>Logo URL<input type="url" name="entity_logo" value="<?php echo esc_attr(seom_get('knowledge_entity_logo','')); ?>"></label>
<label class="seom-full">Entity Description<textarea name="entity_description" rows="3"><?php echo esc_textarea(seom_get('knowledge_entity_description','')); ?></textarea></label>

<div class="seom-full"><h4>Social Profiles</h4><p class="description">These feed straight into the <code>sameAs</code> array of your schema, so Google can connect your website to your social pages.</p></div>
<label>Facebook URL<input type="url" name="social_facebook" value="<?php echo esc_attr(seom_get('knowledge_social_facebook','')); ?>" placeholder="https://facebook.com/yourbrand"></label>
<label>X (Twitter) URL<input type="url" name="social_twitter" value="<?php echo esc_attr(seom_get('knowledge_social_twitter','')); ?>" placeholder="https://x.com/yourbrand"></label>
<label>Instagram URL<input type="url" name="social_instagram" value="<?php echo esc_attr(seom_get('knowledge_social_instagram','')); ?>" placeholder="https://instagram.com/yourbrand"></label>
<label>LinkedIn URL<input type="url" name="social_linkedin" value="<?php echo esc_attr(seom_get('knowledge_social_linkedin','')); ?>" placeholder="https://linkedin.com/company/yourbrand"></label>
<label>YouTube URL<input type="url" name="social_youtube" value="<?php echo esc_attr(seom_get('knowledge_social_youtube','')); ?>" placeholder="https://youtube.com/@yourbrand"></label>
<label class="seom-full">Other SameAs URLs (one per line)<textarea name="entity_sameas" rows="3" placeholder="Wikipedia, Crunchbase, or any other profile not listed above"><?php echo esc_textarea(seom_get('knowledge_entity_sameas','')); ?></textarea></label>

<div class="seom-full"><h4>Advanced Knowledge Graph</h4></div>
<label>Founder Name<input name="founder" value="<?php echo esc_attr(seom_get('knowledge_founder','')); ?>"></label>
<label>Founding Date<input type="date" name="founding_date" value="<?php echo esc_attr(seom_get('knowledge_founding_date','')); ?>"></label>
<label>Corporate Contact Number<input type="tel" name="contact_phone" value="<?php echo esc_attr(seom_get('knowledge_contact_phone','')); ?>" placeholder="+91 XXXXX XXXXX"></label>

<div class="seom-full"><button class="button button-primary">Save Entity Signals</button></div></form><hr><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="seom_gbp_search_entity"><?php wp_nonce_field('seom_gbp_search_entity'); ?><label>Search Google's public Knowledge Graph<input name="entity_query" placeholder="Brand or organization name"></label><button class="button">Find Matching Entity</button></form><?php if($entityResults): ?><div class="seom-table-scroll" style="margin-top:12px"><table class="widefat striped"><thead><tr><th>Name</th><th>Type</th><th>Score</th><th>ID</th><th>Website</th></tr></thead><tbody><?php foreach($entityResults as $e): $r=$e['result']??array(); ?><tr><td><?php echo esc_html($r['name']??''); ?></td><td><?php echo esc_html(is_array($r['@type']??null)?implode(', ', $r['@type']):($r['@type']??'')); ?></td><td><?php echo esc_html($e['resultScore']??''); ?></td><td><code><?php echo esc_html($r['@id']??''); ?></code></td><td><?php if(!empty($r['url'])):?><a target="_blank" rel="noopener" href="<?php echo esc_url($r['url']); ?>">Open</a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div>
