<div class="seom-panel"><h2>Migration & Tools</h2><p>Detected SEO plugins: <strong><?php $d=SEO_Manager_Migration::detect();echo esc_html($d?implode(', ',$d):'None detected'); ?></strong></p><div class="seom-tool-row"><?php foreach(SEO_Manager_Migration::detect() as $name): $slug=strtolower(str_replace(' ','',str_replace('-','',$name)));$src=strpos($slug,'yoast') !== false?'yoast':(strpos($slug,'rankmath') !== false?'rankmath':(strpos($slug,'aioseo') !== false?'aioseo':'')); if(!$src)continue; ?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="seom_import_plugin"><input type="hidden" name="source" value="<?php echo esc_attr($src); ?>"><?php wp_nonce_field('seom_import_plugin'); ?><button class="button">Import from <?php echo esc_html($name); ?></button></form><?php endforeach; ?><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="seom_export"><?php wp_nonce_field('seom_export'); ?><button class="button button-primary">Export SEO Data JSON</button></form></div></div><div class="seom-panel"><h2>System Status</h2><table class="widefat striped"><tbody><?php $info=['WordPress'=>get_bloginfo('version'),'PHP'=>PHP_VERSION,'Plugin'=>SEOM_VERSION,'Theme'=>wp_get_theme()->get('Name'),'Elementor'=>defined('ELEMENTOR_VERSION')?ELEMENTOR_VERSION:'Not active','WooCommerce'=>defined('WC_VERSION')?WC_VERSION:'Not active','Memory Limit'=>ini_get('memory_limit'),'Cron'=>wp_next_scheduled('seom_cleanup_404')?'Scheduled':'Not scheduled','REST API'=>rest_url()];foreach($info as $k=>$v): ?><tr><th><?php echo esc_html($k); ?></th><td><?php echo esc_html($v); ?></td></tr><?php endforeach; ?></tbody></table></div>

<div class="seom-panel"><div class="seom-actions"><div><h2>System diagnostics</h2><p class="description">Check the plugin runtime before you publish important SEO changes.</p></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="seom_repair_rewrites"><?php wp_nonce_field('seom_repair_rewrites'); ?><button class="button">Repair Rewrite Rules</button></form></div><table class="widefat striped"><thead><tr><th>Check</th><th>Status</th><th>Details</th></tr></thead><tbody>
<?php $checks=[
['Core classes',class_exists('SEO_Manager_Meta')&&class_exists('SEO_Manager_Sitemap')&&class_exists('SEO_Manager_Redirects'),'Core SEO modules loaded'],
['Database tables',SEO_Manager_DB::tables_exist(),'Required database tables exist'],
['XML sitemap',seom_get('enable_sitemap',1),'Sitemap output enabled'],
['404 cleanup',wp_next_scheduled('seom_cleanup_404')!==false,'Daily 404 cleanup is scheduled'],
['Google monitor',wp_next_scheduled('seom_google_sync')!==false,'Google SEO update monitor is scheduled'],
['IndexNow queue',wp_next_scheduled('seom_indexnow_queue')!==false,'Search engine queue is scheduled'],
['PHP ZipArchive',class_exists('ZipArchive'),'Required for XLSX import/export'],
]; foreach($checks as $c): ?><tr><td><?php echo esc_html($c[0]); ?></td><td><span class="seom-badge <?php echo $c[1]?'ok':'warn'; ?>"><?php echo $c[1]?'OK':'CHECK'; ?></span></td><td><?php echo esc_html($c[2]); ?></td></tr><?php endforeach; ?>
</tbody></table></div>